name:                gramhs
version:             1.0.2
github:              "Alias Qli/GramHs"
license:             BSD3
author:              "Alias Qli"
maintainer:          "2576814881@qq.com"
copyright:           "2021 Alias Qli"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Alias Qli/GramHs#readme>

dependencies:
- base
- haskell-gi-base
- gi-gtk == 3.0.*
- gi-pango
- gi-gdk
- gi-gio
- gi-gobject
- gi-gtk-declarative
- gi-gtk-declarative-app-simple

- text
- vector
- vector-algorithms
- mtl
- req
- aeson
- websockets
- pipes
- parsec
- bytestring

ghc-options:
- -j
- -O
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wredundant-constraints

default-extensions: 
- ApplicativeDo
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

library:
  source-dirs: src

executables:
  gramhs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - gramhs
